name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16-bullseye
    steps:
      - name: log node version
        run: node -v
      - name: step with docker 
        uses: docker://node:14-alpine3.16
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: step with docker 
        uses: docker://node:14-alpine3.16
        with:
          entrypoint: /usr/local/bin/node
          args: -v

  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine3.15
    steps:
      - name: Log node version
        run: |
          node -v 
          cat /etc/os-release